services:
  - type: web
    name: project-dream-backend
    runtime: docker
    plan: free
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: YTDLP_COOKIES
        sync: false
      - key: YTDLP_COOKIES_PATH
        value: /tmp/yt_cookies.txt
      - key: YTDLP_USE_BROWSER_COOKIES
        value: false
